### PR TITLE
Initial Documentation for Local Development Setup + Contributions

### PR DESCRIPTION
**Pull request by mochsner**
To be reviewed by @delashum ! Figure sooner this gets in, the sooner people might see it & be interested in helping pick out the issues, so I'm going ahead and submitting the PR for review.

### CODE REVIEW

**Comment by mochsner** [comment]
@delashum hey! Just wanted to create the PR since there isn't a whole lot technical going on here. I think it'll be good to improve still, but this is a good start that seems worthwhile to go ahead and add in. As I start diving into actual issues, I might just throw in some improvements to documentation as well.

**Comment by delashum** [comment]
The docs all look good to me. Curious why the removal of `package-lock.json`?

**Comment by mochsner** [comment]
@delashum yeah so good question, and may be something I'll want to add back in. 

For context, I wasn't able to get it running from `npm i` (failure based on a hash of the `package-lock.json`), and every solution I found required the removal of `package-lock.json` to get past that hash error. I'll post that in here when I get back to my dev PC. 

I wasn't spending a ton of time on this, but I did just make a new discovery that I'll want to test this with `package-lock.json` : `npm ci`. This does a clean install, and I think might get around having `package-lock.json` by doing a clean install.

See the answer by K0pernikus here: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by delashum** [comment]
I'm guessing this is because there was a breaking change in the latest major version of `npm`. I'm currently on `7.15.1`. Are you at least a major version below that?

**Comment by mochsner** [comment]
@delashum turns out it was actually something pretty goofy. we need sudo on PopOS when running `npm i` with a `package-lock.json`. Adjusted the documentation and reverted the package-lock.json commit :) Ready to be merged when you are!

**Pull request merged**
